language: python
python:
  - '3.5'
  - '3.6'
  - '3.7'
  - '3.8'
branches:
  only:
  - release
before_install:
  - pip install pytest-runner
  - pip install -r requirements.txt
  - pip install z3-solver
  - pip install SQLAlchemy
install:
  - python setup.py install
script:
  - python setup.py pytest
